<?php
$num=$row["num"];
$outdate=$row["outdate"];			  

$indate=$row["indate"];
$outworkplace=$row["outworkplace"];

$item=$row["item"];			  
$spec=$row["spec"];
$steelnum=$row["steelnum"];			  
$company=$row["company"];
$comment=$row["comment"];
$which=$row["which"];	 	  
$model=$row["model"];	 
$first_writer=$row["first_writer"];
$update_log=$row["update_log"];			  
$search_opt=$row["search_opt"];
$bad_choice=$row["bad_choice"];
$used_width_1=$row["used_width_1"];
$used_width_2=$row["used_width_2"];
$used_width_3=$row["used_width_3"];
$used_width_4=$row["used_width_4"];
$used_width_5=$row["used_width_5"];
$used_length_1=$row["used_length_1"];
$used_length_2=$row["used_length_2"];
$used_length_3=$row["used_length_3"];
$used_length_4=$row["used_length_4"];
$used_length_5=$row["used_length_5"];
$used_num_1=$row["used_num_1"];
$used_num_2=$row["used_num_2"];
$used_num_3=$row["used_num_3"];
$used_num_4=$row["used_num_4"];
$used_num_5=$row["used_num_5"];			  
$supplier=$row["supplier"];			
$method=$row["method"];			
?>